---
  - hosts: localhost
    connection: local
    tasks:
      # Systems Performance, B. Gregg, 2021. Chapter 4.1.2
      - apt: install crisis tools packages
        apt:
          package:
            - procps
            - util-linux
            - sysstat
            - iproute2
            - numactl
            - linux-tools-common
            - bpfcc-tools
            - bpftrace
            - trace-cmd
            - nicstat
            - ethtool
            - tiptop
            - msr-tools 
