#!/bin/bash

function log() {
    echo "$(date) $@"
}

log "Loading xrandr profile via autorandr..."
autorandr --load three

LEFT="HDMI-0"
MIDDLE="DVI-I-1"
RIGHT="DVI-D-0"

# left screen
log "Setting up left screen..."
i3-msg "workspace 1, move workspace to output $LEFT"
i3-msg "workspace 5, move workspace to output $LEFT"
i3-msg "workspace 7, move workspace to output $LEFT"

# middle screen
log "Setting up middle screen..."
i3-msg "workspace 2, move workspace to output $MIDDLE"
i3-msg "workspace 4, move workspace to output $MIDDLE"
i3-msg "workspace 8, move workspace to output $MIDDLE"

# right screen
log "Setting up right screen..."
i3-msg "workspace 3 move workspace to output $RIGHT"
i3-msg "workspace 6, move workspace to output $RIGHT"
i3-msg "workspace 9, move workspace to output $RIGHT"

log "On workspace 1."
i3-msg "workspace 1"

log "All done."
